package com.example.cryptonomicon.models

data class Token(
    val ath: Float,
    val ath_change_percentage: Double,
    val ath_date: String,
    val atl: Double,
    val atl_change_percentage: Double,
    val atl_date: String,
    val circulating_supply: Float,
    val current_price: Float,
    val fully_diluted_valuation: Long,
    val high_24h: Float,
    val id: String,
    val image: String,
    val last_updated: String,
    val low_24h: Float,
    val market_cap: Long,
    val market_cap_change_24h: Double,
    val market_cap_change_percentage_24h: Double,
    val market_cap_rank: Int,
    val max_supply: Float,
    val name: String,
    val price_change_24h: Double,
    val price_change_percentage_24h: Double,
    val roi: Any,
    val symbol: String,
    val total_supply: Float,
    val total_volume: Long
)