package com.example.cryptonomicon.models

data class Token(
    val id: String,
    val name: String,
    val image: Any? = null,
    val symbol: String? = null,
    val current_price: Float? = null,
//    val ath: Float,
//    val ath_change_percentage: Double,
//    val ath_date: String,
//    val atl: Double,
//    val atl_change_percentage: Double,
//    val atl_date: String,
//    val circulating_supply: Float,
//    val fully_diluted_valuation: Long?,
//    val last_updated: String,
//    val low_24h: Float?,
//    val high_24h: Float?,
//    val market_cap: Long,
//    val market_cap_change_24h: Double?,
//    val market_cap_change_percentage_24h: Double?,
//    val price_change_percentage_24h: Double?,
//    val price_change_24h: Double?,
//    val market_cap_rank: Int?,
//    val roi: Any?,
//    val max_supply: Float?,
//    val total_supply: Float?,
//    val total_volume: Long
)